### ISSUE TITLE
MaxListenersExceededWarning when starting app in dev mode using safe-routes

### ISSUE THREAD

**Issue by genox** [yesmeck/safe-routes#121]
When using the safe-routes vite plugin, I get this message while starting in dev mode:

```
(node:79858) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [ReadStream]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
```

The message disappears when commenting out the plugin in vite.config.ts. Are there any known issues?

This is how I configured the plugin:

```
		safeRoutes({
			outDir: 'app/routes',
			strict: true,
		}),
```

It also seems that the app becomes slow in dev mode due to this, so there might be some actual issue here but I'm not sure which information would be helpful to you.

Let me know.

**Comment by yesmeck** [comment]
Hi @genox , can you reproduce the warning in a fresh new react-router project?

**Comment by genox** [comment]
I updated vite to 6.0.3 (was on 5) and the error disappeared. Which is strange, because I had the same error on 6 before downgrading to 5 to troubleshoot without success.

So it magically resolved itself. /shrug

**Comment by HananoshikaYomaru** [comment]
I tried to upgrade to vite 6 and confirm that the problem is still there. I haven't create a reproduce repo yet but my current solution is that I just disable the plugin in dev and enable it in production.
