### ISSUE TITLE
Where does safe-routes typegen output?

### ISSUE THREAD

**Issue by punkpeye** [yesmeck/safe-routes#122]
Where does `safe-routes typegen` output the types?

At the moment, my types are simply:

```
export declare function $path(route: string, ...paramsOrQuery: Array<any>): string;
export declare function $routeId(routeId: string): string;
```

I am trying to understand where does the typegen output and what's missing for me to pick-up those types.

**Comment by punkpeye** [comment]
I was able to fix it with `outDir: 'app/types',`.

**Comment by yesmeck** [comment]
The default output dir is `.react-router/types`.
